---
namespace: "tcharl"
name: "ansible_volumes"
version: "1.0.1"
description: "Manipulates volume groups and logical volumes"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible_volumes"
documentation: "https://github.com/OsgiliathEnterprise/ansible_volumes/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible_volumes"
issues: "https://github.com/OsgiliathEnterprise/ansible_volumes/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "volumes"
  - "volume-groups"
  - "logical-volumes"
  - "linux"
