---
roles:
  # Install a role from Ansible Galaxy.
  - name: mrlesmithjr.manage-lvm

  - name: tcharl.ansible_securehost

  - name: tcharl.ansible_containerization

  - name: geerlingguy.docker

  - name: tcharl.ansible_routing

  - name: tcharl.ansible_nameserver

  - name: tcharl.ansible_hostname

  - name: robertdebock.fail2ban

  - name: robertdebock.bootstrap

  - name: robertdebock.epel

  - name: geerlingguy.ntp
