---
roles:
  # Install a role from Ansible Galaxy.
  - name: tcharl.ansible_manage_lvm
    source: https://galaxy.ansible.com
    path: ../community

  - name: tcharl.ansible_securehost
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_containerization
    source: https://galaxy.ansible.com
    path: ../community
  - name: geerlingguy.docker
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_routing
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_nameserver
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_hostname
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.fail2ban
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.bootstrap
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.epel
    source: https://galaxy.ansible.com
    path: ../community