---

- name: Facts | get current hostname
  ansible.builtin.command: "hostname"
  register: volume_machine_hostname
  changed_when: false

- name: Facts | Gather current mount facts
  ansible.builtin.mount_facts:
    sources:
      - dynamic
  become: true

- name: Show detailed mount info for root filesystem
  ansible.builtin.debug:
    var: item
    verbosity: 2
  loop: "{{ ansible_facts['mount_points'].values() | list }}"
  when: item.mount == "/"
  loop_control:
    label: "{{ item.mount }}"
