---
# tasks file for lvm

- name: ansible-volumes | include prerequisites
  ansible.builtin.include_tasks: prereq.yml

- name: ansible-volumes | loop over vgs
  ansible.builtin.include_tasks: vg.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: avvg
  when:
   - lvm_groups is defined
   - manage_lvm is defined
   - manage_lvm

- name: ansible-volumes | configure autoextends
  ansible.builtin.include_tasks: autoextends.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: avvg
  when:
   - lvm_groups is defined
   - manage_lvm is defined
   - manage_lvm

- name: ansible-volumes | network file system server
  ansible.builtin.include_tasks: nfs-server.yml
  when:
    - lvm_groups is defined
    - q('subelements', lvm_groups, 'lvmetanames', {'skip_missing': True}) | selectattr('expose_nfs', 'defined') | selectattr('expose_nfs', 'equalto', True) | length > 0
    - configure_nfs is defined
    - configure_nfs

- name: ansible-volumes | network file system client
  ansible.builtin.include_tasks: nfs-client.yml
  when:
    - nfs_mountpoints is defined
    - nfs_mountpoints | length > 0
    - configure_nfs is defined
    - configure_nfs
