---

- name: ansible-volumes | nfs-host-mountpoint | datastore
  setup:
  register: datastore_machine
  delegate_facts: true
  delegate_to: "{{ nfs_server.host }}" # TODO concat all masters IPs

- name: ansible-volumes | nfs-host-mountpoint | compute ip if preferred_nic is not set
  ansible.builtin.debug:
    msg: "{{ datastore_machine.ansible_facts['ansible_' + preferred_nic].ipv4.address if preferred_nic is defined else datastore_machine.ansible_facts.ansible_default_ipv4.address | default(datastore_machine.ansible_facts.ansible_all_ipv4_addresses[0]) }}"
  register: datastore_ip

- name: ansible-volumes | nfs-host-mountpoint | loop over mounpoints
  ansible.builtin.include_tasks: nfs-client-fstab-entry.yml
  loop: "{{ nfs_server.mountpoints }}"
  loop_control:
    loop_var: mounpoint
