---
- name: ansible-volumes | nfs-server | nfs-util
  ansible.builtin.package:
    name:
     - nfs-utils
    state: present
  become: true

- name: ansible-volumes | nfs-common | get current hostname
  command: "hostname"
  register: machine_hostname
  changed_when: false

- name: ansible-volumes | nfs-client | nfs common
  ansible.builtin.include_tasks: nfs-common.yml

- name: ansible-volumes | nfs-client | iterate over mountpoints
  ansible.builtin.include_tasks: nfs-host-mountpoint.yml
  loop: "{{ nfs_mountpoints }}"
  loop_control:
    loop_var: nfs_server

- name: ansible-volumes | nfs-client | configure kerb ticket auto renewal
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: "{{ item.regexp }}"
    insertafter: '^\[domain/{{ company_domain }}\]'
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^krb5_renewable_lifetime = 50d', line: 'krb5_renewable_lifetime = 50d' }
    - { regexp: '^krb5_renew_interval = 3600', line: 'krb5_renew_interval = 3600' }
  become: true

- name: ansible-volumes | nfs-client | restart sssd after modifications
  ansible.builtin.systemd:
    name: "sssd"
    state: restarted
    enabled: true
  become: true
