---

- name: ansible-volumes | nfs-client-entry | add mount to fstab
  ansible.posix.mount:
    src: "{{ nfs_server.host }}:{{ mounpoint.remote }}"
    path: "{{ mounpoint.local }}"
    opts: sec=krb5p,rw
    state: mounted
    fstype: nfs4
  become: true