---

- name: ansible-volumes | nfs-host-mountpoint | activate sssd autofs
  ansible.builtin.ini_file:
    path: /etc/sssd/sssd.conf
    section: sssd
    option: services
    value: 'nss, pam, ssh, sudo, autofs'
    backup: yes
    state: present
  become: yes

- name: ansible-volumes | nfs-host-mountpoint | loop over mounpoints
  ansible.builtin.include_tasks: nfs-client-automount-entry.yml
  loop: "{{ nfs_server.mountpoints }}"
  loop_control:
    loop_var: mounpoint
