---

- name: Prereq | Install prerequisite
  ansible.builtin.package:
    name: xfsprogs
    state: present
  become: true
  loop: "{{ lookup('subelements', lvm_groups, 'lvmetanames', {'skip_missing': True}, wantlist=True) | unique }}"
  loop_control:
    loop_var: lv
  when:
    - lv.1 is defined
    - lv.1 != "None"
    - lv.1.filesystem is defined
    - lv.1.filesystem == "xfs"
    - lv.1.create is defined
    - lv.1.create|bool


- name: Prereq | Gather current mount facts
  ansible.builtin.mount_facts:
    sources:
      - all
  become: true

- name: Prereq | Show detailed mount info for root filesystem
  ansible.builtin.debug:
    var: item
    verbosity: 2
  loop: "{{ ansible_facts['mount_points'].values() | list }}"
  when: item.mount == "/"
  loop_control:
    label: "{{ item.mount }}"

- name: Prereq | include manage_lvm role | centos
  ansible.builtin.import_role:
    name: mrlesmithjr.manage_lvm
