---
# tasks file for lvm
- name: Vg  | create volume for each lv
  ansible.builtin.include_tasks: lv.yml
  loop: "{{ avvg.lvmetanames }}"
  loop_control:
    loop_var: avlv
  when: avlv is defined and avlv != 'None'

- name: Vg  | create pool for each lv
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ avvg.lvmetanames }}"
  loop_control:
    loop_var: avlv
  when: avlv is defined and avlv != 'None' and avlv.metadata is defined
