---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: consumer.osgiliath.test
    box: fedora/34-cloud-base
    provider_options:
      cpus: 2
      memory: 3096
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ipaservers
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
  - name: datastore.osgiliath.test
    box: fedora/34-cloud-base
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ipaclients
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-volumes.vdi'"
      - "persistent_storage.size = 10"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/..:${MOLECULE_PROJECT_DIRECTORY}/../community:${ANSIBLE_ROLES_PATH}"
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${ANSIBLE_COLLECTIONS_PATH}"
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: nfs
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
 #   - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
