---
- name: Converge
  hosts: all
  vars:
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvmetanames:
          - lvname: thinpool
            size: 40%VG
            opts: "--wipesignatures y"
            create: true
            metadata: non-persistent/thinpoolmeta
            autoextendtreshold: 80
            autoextendpercent: 20
            filesystem: xfs
            mntp: /var/lib/docker
            mount: true
          - lvname: thinpoolmeta
            size: 10%VG
            opts: "--wipesignatures y"
            create: true
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            mntp: /var/nfs
            mount: true
    manage_lvm: true
  tasks:
    - name: Display dev
      ansible.builtin.command: "ls /dev"
      changed_when: false
      register: result

    - name: "debug result"
      ansible.builtin.debug:
        var: result
  roles:
    - role: tcharl.ansible_volumes
